# Generated by Django 5.1.7 on 2025-03-16 01:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('reaction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('SC', 'SC'), ('CC', 'CC'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('hospitalizations', models.TextField(blank=True, null=True)),
                ('implants', models.TextField(blank=True, null=True)),
                ('smoking_status', models.BooleanField(default=False)),
                ('alcohol_consumption', models.CharField(choices=[('None', 'None'), ('Occasional', 'Occasional'), ('Regular', 'Regular')], default='None', max_length=50)),
                ('diet_and_exercise', models.TextField(blank=True, null=True)),
                ('prostate_screening', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10)),
                ('cervical_cancer_screening', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10)),
                ('breast_cancer_screening', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10)),
                ('last_vital_signs', models.TextField(blank=True, null=True)),
                ('recent_lab_results', models.ImageField(blank=True, null=True, upload_to='lab_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergies', models.ManyToManyField(blank=True, to='medical_history.allergy')),
                ('chronic_conditions', models.ManyToManyField(blank=True, to='medical_history.chroniccondition')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
                ('past_surgeries', models.ManyToManyField(blank=True, to='medical_history.surgicalhistory')),
            ],
        ),
    ]
